#!/bin/bash
#$ -q gpu.q
#$ -N deepag
#$ -l mem_req=10G
#$ -l h_vmem=20G
#$ -o /sequoia/data1/orybkin/FocalNet/logs/deepag.out
#$ -e /sequoia/data1/orybkin/FocalNet/logs/deepag.err
#$ -wd /sequoia/data1/orybkin/FocalNet/deepag/bin/deepag/
#$ -m eba
#$ -M oleh.rybkin@inria.fr
#$ -pe serial 1

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-7.0/lib64:/usr/local/cuda-7.0/lib
/sequoia/data2/matlab/matlab-2015a/linux64/bin/matlab -nodisplay -nosplash -nodesktop -r "bougnoux_script;"
